version: '3.6'

services:
  octoprint-flsun:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 1980:80
    devices:    
      - /dev/serial/by-id/usb-marlinfw.org_Marlin_USB_Device_03030F0D534D08544DFC0B33F5000006-if00:/dev/ttyACM0
      # - /dev/video0:/dev/video0
    #environment:
    #  - ENABLE_MJPG_STREAMER=true
    volumes:
     - octoprint-flsun:/octoprint    
  
  octoprint-cocoon:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 1981:80
    devices:    
      - /dev/serial/by-id/usb-1a86_USB2.0-Serial-if00-port0:/dev/ttyUSB0
      # - /dev/video0:/dev/video0
    #environment:
    #  - ENABLE_MJPG_STREAMER=true
    volumes:
     - octoprint-cocoon:/octoprint

  config-editor:
    image: linuxserver/code-server
    ports:
      - 8443:8443
    depends_on:
      - octoprint-cocoon
      - octoprint-flsun
    restart: unless-stopped
    environment:
      - PUID=0
      - GUID=0
      - TZ=Australia/Melbourne
    volumes:
      - octoprint-flsun:/printers/flsun
      - octoprint-cocoon:/printers/cocoon

volumes:
  octoprint-flsun:
  octoprint-cocoon: